public enum States { 
    EnterMenu,
    MainMenu,
    StoryMenu,
    OptionsMenu,
    Extrasmenu,
    QuitMenu,
    NewGame,
    LoadGame,
    Credits,
    ChapterSelect,
    Gameplay,
    Controls,
    keyBindings,
    Display,
    Graphics,
    Audio,
    Language
}